site_name: My Docs

theme:
  feature:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
  language: ja
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      secondary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      secondary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      secondary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: "Noto Sans JP"
    code: "Consolas"
  # custom_dir: overrides

plugins:
  - tags:
      tags_file: tags.md
  - search
  - mkdocstrings


markdown_extensions:
  - footnotes
  - meta
  - plantuml_markdown:
      server: http://plantuml:8080
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - def_list
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
      use_pygments: true
      noclasses: true

extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - stylesheets/extra.css
